language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TRACEVIEW_DEBUG=1
        
install:
  - wget https://files.appneta.com/install_appneta.sh
  - sudo sh ./install_appneta.sh $TRACEVIEW_API
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get golang.org/x/net/context github.com/stretchr/testify/assert gopkg.in/mgo.v2/bson
  - go get github.com/opentracing/opentracing-go

script:
  - cd $GOPATH/src/github.com/tracelytics/go-traceview/v1/tv
  - go build -v github.com/tracelytics/go-traceview/v1/tv github.com/tracelytics/go-traceview/v1/tv/internal/traceview
  - go test -v -covermode=atomic -coverprofile=cov.out -coverpkg github.com/tracelytics/go-traceview/v1/tv/internal/traceview,github.com/tracelytics/go-traceview/v1/tv
  - go test -v -tags traceview -covermode=atomic -coverprofile=covtv.out -coverpkg github.com/tracelytics/go-traceview/v1/tv/internal/traceview,github.com/tracelytics/go-traceview/v1/tv
  - pushd internal/traceview/
  - go test -v -covermode=atomic -coverprofile=cov.out
  - go test -v -tags traceview -covermode=atomic -coverprofile=covtv.out
  - popd
  - pushd ottv
  - go test -v -covermode=atomic -coverprofile=cov.out -coverpkg github.com/tracelytics/go-traceview/v1/tv/internal/traceview,github.com/tracelytics/go-traceview/v1/tv/ottv,github.com/tracelytics/go-traceview/v1/tv
  - go test -v -tags traceview -covermode=atomic -coverprofile=covtv.out -coverpkg github.com/tracelytics/go-traceview/v1/tv/internal/traceview,github.com/tracelytics/go-traceview/v1/tv/ottv,github.com/tracelytics/go-traceview/v1/tv
  - popd
  - gocovmerge cov.out covtv.out internal/traceview/cov.out internal/traceview/covtv.out ottv/cov.out ottv/covtv.out > covmerge.out
  - travis_retry $GOPATH/bin/goveralls -coverprofile=covmerge.out -service=travis-ci -repotoken $COVERALLS_TOKEN
